# Generated by Django 4.2 on 2023-04-30 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Primeiro Nome')),
                ('last_name', models.CharField(max_length=50, verbose_name='Sobrenome')),
                ('phone', models.CharField(max_length=50, unique=True, verbose_name='Sobrenome')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='data de entrada')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
            ],
        ),
    ]
